export type LanguageItem = {
  name: string;
  value: string;
  alias?: string[];
};

export const languages = [
  { name: 'Plain Text', value: 'plaintext', alias: ['text', 'txt'] },
  { name: '1C', value: '1c', alias: [] },
  { name: 'ABNF', value: 'abnf', alias: [] },
  { name: 'Apache Access Log', value: 'accesslog', alias: [] },
  { name: 'ActionScript', value: 'actionscript', alias: ['as'] },
  { name: 'Ada', value: 'ada', alias: [] },
  { name: 'AngelScript', value: 'angelscript', alias: ['asc'] },
  { name: 'Apache config', value: 'apache', alias: ['apacheconf'] },
  { name: 'AppleScript', value: 'applescript', alias: ['osascript'] },
  { name: 'ArcGIS Arcade', value: 'arcade', alias: [] },
  { name: 'Arduino', value: 'arduino', alias: ['ino'] },
  { name: 'ARM Assembly', value: 'armasm', alias: ['arm'] },
  { name: 'AsciiDoc', value: 'asciidoc', alias: ['adoc'] },
  { name: 'AspectJ', value: 'aspectj', alias: [] },
  { name: 'AutoHotkey', value: 'autohotkey', alias: ['ahk'] },
  { name: 'AutoIt', value: 'autoit', alias: [] },
  { name: 'AVR Assembly', value: 'avrasm', alias: [] },
  { name: 'Awk', value: 'awk', alias: [] },
  { name: 'X++', value: 'axapta', alias: ['x++'] },
  { name: 'Bash', value: 'bash', alias: ['sh'] },
  { name: 'BASIC', value: 'basic', alias: [] },
  { name: 'BNF', value: 'bnf', alias: [] },
  { name: 'Brainfuck', value: 'brainfuck', alias: ['bf'] },
  { name: 'C', value: 'c', alias: ['h'] },
  { name: 'C/AL', value: 'cal', alias: [] },
  { name: "Cap'n Proto", value: 'capnproto', alias: ['capnp'] },
  { name: 'Ceylon', value: 'ceylon', alias: [] },
  { name: 'Clean', value: 'clean', alias: ['icl', 'dcl'] },
  { name: 'Clojure', value: 'clojure', alias: ['clj', 'edn'] },
  { name: 'Clojure REPL', value: 'clojure-repl', alias: [] },
  { name: 'CMake', value: 'cmake', alias: ['cmake.in'] },
  {
    name: 'CoffeeScript',
    value: 'coffeescript',
    alias: ['coffee', 'cson', 'iced'],
  },
  { name: 'Coq', value: 'coq', alias: [] },
  { name: 'Caché ObjectScript', value: 'cos', alias: ['cls'] },
  {
    name: 'C++',
    value: 'cpp',
    alias: ['cc', 'c++', 'h++', 'hpp', 'hh', 'hxx', 'cxx'],
  },
  { name: 'crmsh', value: 'crmsh', alias: ['crm', 'pcmk'] },
  { name: 'Crystal', value: 'crystal', alias: ['cr'] },
  { name: 'C#', value: 'csharp', alias: ['cs', 'c#'] },
  { name: 'CSP', value: 'csp', alias: [] },
  { name: 'CSS', value: 'css', alias: [] },
  { name: 'D', value: 'd', alias: [] },
  { name: 'Dart', value: 'dart', alias: [] },
  { name: 'Delphi', value: 'delphi', alias: ['dpr', 'dfm', 'pas', 'pascal'] },
  { name: 'Diff', value: 'diff', alias: ['patch'] },
  { name: 'Django', value: 'django', alias: ['jinja'] },
  { name: 'DNS Zone', value: 'dns', alias: ['bind', 'zone'] },
  { name: 'Dockerfile', value: 'dockerfile', alias: ['docker'] },
  { name: 'Batch file (DOS)', value: 'dos', alias: ['bat', 'cmd'] },
  { name: 'DSConfig', value: 'dsconfig', alias: [] },
  { name: 'Device Tree', value: 'dts', alias: [] },
  { name: 'Dust', value: 'dust', alias: ['dst'] },
  { name: 'EBNF', value: 'ebnf', alias: [] },
  { name: 'Elixir', value: 'elixir', alias: ['ex', 'exs'] },
  { name: 'Elm', value: 'elm', alias: [] },
  { name: 'ERB', value: 'erb', alias: [] },
  { name: 'Erlang', value: 'erlang', alias: ['erl'] },
  { name: 'Erlang REPL', value: 'erlang-repl', alias: [] },
  { name: 'Excel formulae', value: 'excel', alias: ['xlsx', 'xls'] },
  { name: 'FIX', value: 'fix', alias: [] },
  { name: 'Flix', value: 'flix', alias: [] },
  { name: 'Fortran', value: 'fortran', alias: ['f90', 'f95'] },
  { name: 'F#', value: 'fsharp', alias: ['fs', 'f#'] },
  { name: 'GAMS', value: 'gams', alias: ['gms'] },
  { name: 'GAUSS', value: 'gauss', alias: ['gss'] },
  { name: 'G-code (ISO 6983)', value: 'gcode', alias: ['nc'] },
  { name: 'Gherkin', value: 'gherkin', alias: ['feature'] },
  { name: 'GLSL', value: 'glsl', alias: [] },
  { name: 'GML', value: 'gml', alias: [] },
  { name: 'Go', value: 'go', alias: ['golang'] },
  { name: 'Golo', value: 'golo', alias: [] },
  { name: 'Gradle', value: 'gradle', alias: [] },
  { name: 'GraphQL', value: 'graphql', alias: ['gql'] },
  { name: 'Groovy', value: 'groovy', alias: [] },
  { name: 'HAML', value: 'haml', alias: [] },
  {
    name: 'Handlebars',
    value: 'handlebars',
    alias: ['hbs', 'html.hbs', 'html.handlebars', 'htmlbars'],
  },
  { name: 'Haskell', value: 'haskell', alias: ['hs'] },
  { name: 'Haxe', value: 'haxe', alias: ['hx'] },
  { name: 'HSP', value: 'hsp', alias: [] },
  { name: 'HTTP', value: 'http', alias: ['https'] },
  { name: 'Hy', value: 'hy', alias: ['hylang'] },
  { name: 'Inform 7', value: 'inform7', alias: ['i7'] },
  { name: 'TOML, INI', value: 'ini', alias: ['toml'] },
  { name: 'IRPF90', value: 'irpf90', alias: [] },
  { name: 'ISBL', value: 'isbl', alias: [] },
  { name: 'Java', value: 'java', alias: ['jsp'] },
  {
    name: 'JavaScript',
    value: 'javascript',
    alias: ['js', 'jsx', 'mjs', 'cjs'],
  },
  { name: 'JBoss CLI', value: 'jboss-cli', alias: ['wildfly-cli'] },
  { name: 'JSON', value: 'json', alias: [] },
  { name: 'Julia', value: 'julia', alias: [] },
  { name: 'Julia REPL', value: 'julia-repl', alias: ['jldoctest'] },
  { name: 'Kotlin', value: 'kotlin', alias: ['kt', 'kts'] },
  { name: 'Lasso', value: 'lasso', alias: ['ls', 'lassoscript'] },
  { name: 'LaTeX', value: 'latex', alias: ['tex'] },
  { name: 'LDIF', value: 'ldif', alias: [] },
  { name: 'Leaf', value: 'leaf', alias: [] },
  { name: 'Less', value: 'less', alias: [] },
  { name: 'Lisp', value: 'lisp', alias: [] },
  { name: 'LiveCode', value: 'livecodeserver', alias: [] },
  { name: 'LiveScript', value: 'livescript', alias: ['ls'] },
  { name: 'LLVM IR', value: 'llvm', alias: [] },
  { name: 'LSL', value: 'lsl', alias: [] },
  { name: 'Lua', value: 'lua', alias: [] },
  { name: 'Makefile', value: 'makefile', alias: ['mk', 'mak', 'make'] },
  { name: 'Markdown', value: 'markdown', alias: ['md', 'mkdown', 'mkd'] },
  { name: 'Mathematica', value: 'mathematica', alias: ['mma', 'wl'] },
  { name: 'Matlab', value: 'matlab', alias: [] },
  { name: 'Maxima', value: 'maxima', alias: [] },
  { name: 'MEL', value: 'mel', alias: [] },
  { name: 'Mercury', value: 'mercury', alias: ['m', 'moo'] },
  { name: 'MIPS Assembly', value: 'mipsasm', alias: ['mips'] },
  { name: 'Mizar', value: 'mizar', alias: [] },
  { name: 'Mojolicious', value: 'mojolicious', alias: [] },
  { name: 'Monkey', value: 'monkey', alias: [] },
  { name: 'MoonScript', value: 'moonscript', alias: ['moon'] },
  { name: 'N1QL', value: 'n1ql', alias: [] },
  { name: 'Nested Text', value: 'nestedtext', alias: ['nt'] },
  { name: 'Nginx', value: 'nginx', alias: ['nginxconf'] },
  { name: 'Nim', value: 'nim', alias: [] },
  { name: 'Nix', value: 'nix', alias: ['nixos'] },
  { name: 'Node REPL', value: 'node-repl', alias: [] },
  { name: 'NSIS', value: 'nsis', alias: [] },
  {
    name: 'Objective-C',
    value: 'objectivec',
    alias: ['mm', 'objc', 'obj-c', 'obj-c++', 'objective-c++'],
  },
  { name: 'OCaml', value: 'ocaml', alias: ['ml'] },
  { name: 'OpenSCAD', value: 'openscad', alias: ['scad'] },
  { name: 'Oxygene', value: 'oxygene', alias: [] },
  { name: 'Parser3', value: 'parser3', alias: [] },
  { name: 'Perl', value: 'perl', alias: ['pl', 'pm'] },
  { name: 'Packet Filter config', value: 'pf', alias: ['pf.conf'] },
  { name: 'PostgreSQL', value: 'pgsql', alias: ['postgres', 'postgresql'] },
  { name: 'PHP', value: 'php', alias: [] },
  { name: 'PHP Template', value: 'php-template', alias: [] },
  { name: 'Pony', value: 'pony', alias: [] },
  { name: 'PowerShell', value: 'powershell', alias: ['pwsh', 'ps', 'ps1'] },
  { name: 'Processing', value: 'processing', alias: ['pde'] },
  { name: 'Python profiler', value: 'profile', alias: [] },
  { name: 'Prolog', value: 'prolog', alias: [] },
  { name: '.properties', value: 'properties', alias: [] },
  { name: 'Protocol Buffers', value: 'protobuf', alias: [] },
  { name: 'Puppet', value: 'puppet', alias: ['pp'] },
  { name: 'PureBASIC', value: 'purebasic', alias: ['pb', 'pbi'] },
  { name: 'Python', value: 'python', alias: ['py', 'gyp', 'ipython'] },
  { name: 'Python REPL', value: 'python-repl', alias: ['pycon'] },
  { name: 'Q', value: 'q', alias: ['k', 'kdb'] },
  { name: 'QML', value: 'qml', alias: ['qt'] },
  { name: 'R', value: 'r', alias: [] },
  { name: 'ReasonML', value: 'reasonml', alias: ['re'] },
  { name: 'RenderMan RIB', value: 'rib', alias: [] },
  { name: 'Roboconf', value: 'roboconf', alias: ['graph', 'instances'] },
  { name: 'MikroTik RouterOS', value: 'routeros', alias: ['mikrotik'] },
  { name: 'RenderMan RSL', value: 'rsl', alias: [] },
  {
    name: 'Ruby',
    value: 'ruby',
    alias: ['rb', 'gemspec', 'podspec', 'thor', 'irb'],
  },
  { name: 'Oracle Rules Language', value: 'ruleslanguage', alias: [] },
  { name: 'Rust', value: 'rust', alias: ['rs'] },
  { name: 'SAS', value: 'sas', alias: [] },
  { name: 'Scala', value: 'scala', alias: [] },
  { name: 'Scheme', value: 'scheme', alias: ['scm'] },
  { name: 'Scilab', value: 'scilab', alias: ['sci'] },
  { name: 'SCSS', value: 'scss', alias: [] },
  { name: 'Shell Session', value: 'shell', alias: ['console', 'shellsession'] },
  { name: 'Smali', value: 'smali', alias: [] },
  { name: 'Smalltalk', value: 'smalltalk', alias: ['st'] },
  { name: 'SML (Standard ML)', value: 'sml', alias: ['ml'] },
  { name: 'SQF', value: 'sqf', alias: [] },
  { name: 'SQL', value: 'sql', alias: [] },
  { name: 'Stan', value: 'stan', alias: ['stanfuncs'] },
  { name: 'Stata', value: 'stata', alias: ['do', 'ado'] },
  { name: 'STEP Part 21', value: 'step21', alias: ['p21', 'step', 'stp'] },
  { name: 'Stylus', value: 'stylus', alias: ['styl'] },
  { name: 'SubUnit', value: 'subunit', alias: [] },
  { name: 'Swift', value: 'swift', alias: [] },
  { name: 'Tagger Script', value: 'taggerscript', alias: [] },
  { name: 'Test Anything Protocol', value: 'tap', alias: [] },
  { name: 'Tcl', value: 'tcl', alias: ['tk'] },
  { name: 'Thrift', value: 'thrift', alias: [] },
  { name: 'TP', value: 'tp', alias: [] },
  { name: 'Twig', value: 'twig', alias: ['craftcms'] },
  { name: 'TypeScript', value: 'typescript', alias: ['ts', 'tsx'] },
  { name: 'Vala', value: 'vala', alias: [] },
  { name: 'Visual Basic .NET', value: 'vbnet', alias: ['vb'] },
  { name: 'VBScript', value: 'vbscript', alias: ['vbs'] },
  { name: 'VBScript in HTML', value: 'vbscript-html', alias: [] },
  { name: 'Verilog', value: 'verilog', alias: ['v', 'sv', 'svh'] },
  { name: 'VHDL', value: 'vhdl', alias: [] },
  { name: 'Vim Script', value: 'vim', alias: [] },
  { name: 'WebAssembly', value: 'wasm', alias: [] },
  { name: 'Wren', value: 'wren', alias: [] },
  { name: 'Intel x86 Assembly', value: 'x86asm', alias: [] },
  { name: 'XL', value: 'xl', alias: ['tao'] },
  {
    name: 'HTML, XML',
    value: 'xml',
    alias: [
      'html',
      'xhtml',
      'rss',
      'atom',
      'xjb',
      'xsd',
      'xsl',
      'plist',
      'wsf',
      'svg',
    ],
  },
  { name: 'XQuery', value: 'xquery', alias: ['xpath', 'xq'] },
  { name: 'YAML', value: 'yaml', alias: ['yml'] },
  { name: 'Zephir', value: 'zephir', alias: ['zep'] },
];

export const getLanguageByValueOrAlias = (
  valueOrAlias: string
): LanguageItem | null => {
  if (!valueOrAlias) {
    return null;
  }
  const v = valueOrAlias.toLocaleLowerCase();
  const language = languages.find(
    (language) => language.value === v || language.alias.includes(v)
  );
  return language;
};

export const getLanguageByValue = (value: string): LanguageItem | null => {
  if (!value) {
    return null;
  }
  const language = languages.find((language) => language.value === value);
  return language;
};
